name: Deploy to Server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS || 'optional' }}

      - name: Deploy with rsync
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
            ./dist/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_STATIC_DIR }}/

      - name: Reload Nginx
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            'sudo systemctl reload nginx'

  refresh-cdn:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Aliyun CLI
        run: |
          wget -q https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz
          tar xzf aliyun-cli-linux-latest-amd64.tgz
          sudo mv aliyun /usr/local/bin/
          aliyun configure set --profile default --mode AK \
            --region cn-hangzhou \
            --access-key-id ${{ secrets.ALIYUN_ACCESS_KEY_ID }} \
            --access-key-secret ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      - name: Wait for deployment to propagate
        run: sleep 5

      - name: Refresh CDN Cache (Clear)
        run: |
          echo "=== Starting CDN Cache Refresh ==="
          while IFS= read -r url; do
            if [[ -n "$url" ]]; then
              echo "Refreshing: $url"
              aliyun cdn RefreshObjectCaches \
                --ObjectPath "$url" \
                --ObjectType "Directory"
            fi
          done < .github/urllist.txt

      - name: Pre-warm CDN Cache (Push)
        run: |
          echo "=== Starting CDN Cache Preload ==="
          while IFS= read -r url; do
            if [[ -n "$url" ]]; then
              echo "Preloading: $url"
              aliyun cdn PushObjectCache \
                --ObjectPath "$url" \
                --Area "domestic"
            fi
          done < .github/urllist.txt
